spring.ai.openai.api-key=${OPENAI_API_KEY}
app.resource=classpath:company-recharge.txt

spring.ai.openai.embedding.model=text-embedding-3-small
spring.ai.openai.chat.model=gpt-4o-mini

spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.username=postgres
spring.datasource.password=password123

spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

logging.level.org.springframework.ai=DEBUG
logging.level.com.openai=DEBUG